// Generated by scripts/build-quran-data.js - do not edit by hand.
//
// One entry per bundled translation. `id` is both the translator key passed
// to the Qur'an client and the basename of its file in data/quran/.

const editions = [
  {
    id: "tur-abdulbakigolpin",
    name: "Abdülbaki Gölpınarlı",
    description: null,
  },
  {
    id: "tur-ademugur",
    name: "Adem Uğur",
    description: null,
  },
  {
    id: "tur-alibulac",
    name: "Ali Bulaç",
    description: "Kur'an-ı Kerim ve Türkçe Anlamı",
  },
  {
    id: "tur-alifikriyavuz",
    name: "Ali Fikri Yavuz",
    description: null,
  },
  {
    id: "tur-celalyldrm",
    name: "Celal Yıldırım",
    description: null,
  },
  {
    id: "tur-diyanetisleri",
    name: "Diyanet İşleri",
    description: "Kur'an-ı Kerim Türkçe Meali",
  },
  {
    id: "tur-diyanetvakfi",
    name: "Diyanet Vakfı",
    description: null,
  },
  {
    id: "tur-edipyuksel",
    name: "Edip Yüksel",
    description: "Mesaj: Kuran Çevirisi",
  },
  {
    id: "tur-elmalilihamdiya",
    name: "Elmalılı Hamdi Yazır",
    description: "Kur'an-ı Kerim ve Yüce Meali",
  },
  {
    id: "tur-elmallsadelesti",
    name: "Elmalılı (sadeleştirilmiş)",
    description: null,
  },
  {
    id: "tur-elmallsadelesti1",
    name: "Elmalılı (sadeleştirilmiş 2)",
    description: null,
  },
  {
    id: "tur-fizilalilkuran",
    name: "Fizilal-il Kuran",
    description: null,
  },
  {
    id: "tur-gultekinonan",
    name: "Gültekin Onan",
    description: null,
  },
  {
    id: "tur-hasanbasricanta",
    name: "Hasan Basri Çantay",
    description: "Kur'an-ı Hakim ve Meal-i Kerim",
  },
  {
    id: "tur-ibnikesir",
    name: "İbni Kesir",
    description: null,
  },
  {
    id: "tur-iskenderalimihr",
    name: "İskender Ali Mihr",
    description: null,
  },
  {
    id: "tur-muhammedesed",
    name: "Muhammed Esed",
    description: "Kur'an Mesajı",
  },
  {
    id: "tur-muslimshahin",
    name: "Muslim Shahin",
    description: null,
  },
  {
    id: "tur-sabanpiris",
    name: "Şaban Piriş",
    description: "Kur'an-ı Kerim Türkçe Anlamı",
  },
  {
    id: "tur-shabanbritch",
    name: "Shaban Britch",
    description: null,
  },
  {
    id: "tur-suatyildirim",
    name: "Suat Yıldırım",
    description: "Kuran-ı Kerim ve Meali",
  },
  {
    id: "tur-suleymanates",
    name: "Süleyman Ateş",
    description: "Kur'an-ı Kerim ve Yüce Meali",
  },
  {
    id: "tur-tefhimulkuran",
    name: "Tefhimu'l Kur'an",
    description: null,
  },
  {
    id: "tur-wwwislamhouseco",
    name: "İslamhouse.com",
    description: null,
  },
  {
    id: "tur-yasarnuriozturk",
    name: "Yaşar Nuri Öztürk",
    description: "Kur'an-ı Kerim Meali",
  },
  {
    id: "tur-yasarnuriozturk1",
    name: "Yaşar Nuri Öztürk (2)",
    description: null,
  },
  {
    id: "tur-ynozturk",
    name: "Y. N. Öztürk",
    description: null,
  },
];

module.exports = { editions };
